stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: chess-app:latest

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .

test:
  stage: test
  script:
    - docker run $DOCKER_IMAGE npm test

deploy:
  stage: deploy
  environment: staging
  script:
    - docker-compose -f docker-compose.staging.yml up -d
