apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chess-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: chess.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chess-backend-service
                port:
                  number: 80
