apiVersion: v1
kind: Service
metadata:
  name: chess-backend-service
  labels:
    app: chess-backend
spec:
  type: LoadBalancer

  selector:
    app: chess-backend

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000

